version: "3"
services: 
    reverseproxy:
        image: sakshee19/reverseproxy:1.0.0
        ports:
            - 8001:8001
        # restart: always
        depends_on: 
            - backend-user
            - backend-feed
    backend-user:
        image: sakshee19/udacity-user-service:1.0.0
        volumes:
            - $HOME/.aws:/root/.aws
        environment: 
            POSTGRES_USERNAME: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
            POSTGRES_DATABASE: $POSTGRES_DATABASE
            POSTGRES_HOST: $POSTGRES_HOST 
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"
    backend-feed:
        image: sakshee19/udacity-feed-service:1.0.0
        volumes:
            - $HOME/.aws:/root/.aws
        environment: 
            POSTGRES_USERNAME: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
            POSTGRES_DATABASE: $POSTGRES_DATABASE
            POSTGRES_HOST: $POSTGRES_HOST 
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"
    frontend:
        image: sakshee19/udacity-udagram-frontend:1.0.0
        ports: 
            - "8100:80"