version: '3'
services:
    reverseproxy:
        build: 
            context: .
        image: sakshee19/reverseproxy:1.0.0
    backend_user:
        build:
            context: ../user-service
        image: sakshee19/udacity-user-service:1.0.0
    backend_feed:
        build:
            context: ../feed-service
        image: sakshee19/udacity-feed-service:1.0.0
    frontend:
        build:
            context: ../udacity-c2-frontend
        image: sakshee19/udacity-udagram-frontend:1.0.0


# version: "3"
# services: 
#     reverseproxy:
#         build:   
#             context: .
#             image: sakshee19/reverseproxy
#     backend-user:
#         build: 
#             context: ../../udacity-user-service
#             image: sakshee19/udacity-user-service
#     backend-feed:
#         build: 
#             context: ../../udacity-feed-service
#             image: sakshee19/udacity-feed-service
#     frontend:
#         build:
#             context: ../../udacity-udagram-frontend
#             image: sakshee19/udacity-udagram-frontend:latest