apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: sakshee19/udacity-user-service
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: env-config
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: env-config
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: env-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: env-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: env-secret
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: env-secret
      restartPolicy: Always


